// Theme Downloader — fetches pre-built theme templates from GitHub / Gitee
// Mirrors the legacy wewrite theme-manager.ts download pattern.
// GitHub primary, Gitee fallback for users in China.
//
// Index resolution order:
// 1. themes.json (if present in the repo — generated by scanThemes.ts)
// 2. Directory listing via API (GitHub / Gitee contents API)
// 3. Built-in fallback templates (when both remotes are unreachable)

import type { App } from 'obsidian';
import { Notice, requestUrl } from 'obsidian';
import { t } from '../i18n';
import { createLogger } from '../utils/logger';

const log = createLogger('Styles');

// Raw content URLs (for themes.json and raw .md content)
const GITHUB_RAW_BASE = 'https://raw.githubusercontent.com/learnerchen-forever/wewrite/refs/heads/master/themes/';
const GITEE_RAW_BASE = 'https://gitee.com/northern_bank/wewrite/raw/master/themes/';

// API URLs (for directory listing fallback when themes.json is absent)
const GITHUB_API_THEMES = 'https://api.github.com/repos/learnerchen-forever/wewrite/contents/themes/';
const GITEE_API_THEMES = 'https://gitee.com/api/v5/repos/northern_bank/wewrite/contents/themes/';

interface ThemeEntry {
  name: string;
  file: string;
}

interface ThemesIndex {
  themes: ThemeEntry[];
}

interface ApiDirEntry {
  name: string;
  download_url?: string;
  url?: string;
}

export class ThemeDownloader {
  private app: App;

  constructor(app: App) {
    this.app = app;
  }

  async downloadThemes(saveDir: string): Promise<void> {
    if (!saveDir) {
      new Notice(t('notice.templates_need_styles_dir'));
      return;
    }

    new Notice(t('notice.templates_downloading'));

    // Try GitHub first, then Gitee
    let result = await this.tryDownload(GITHUB_RAW_BASE, GITHUB_API_THEMES, saveDir);
    if (result === 'unreachable') {
      result = await this.tryDownload(GITEE_RAW_BASE, GITEE_API_THEMES, saveDir);
    }

    if (result === 'unreachable') {
      new Notice(t('notice.templates_offline'));
      await this.saveFallbackTemplates(saveDir);
    }
  }

  /**
   * Attempt to download themes from a single remote.
   * Returns 'ok' on success, 'unreachable' if the remote is down.
   */
  private async tryDownload(
    rawBase: string,
    apiUrl: string,
    saveDir: string,
  ): Promise<'ok' | 'unreachable'> {
    // ── Step 1: probe network reachability via themes.json ──
    let themes: ThemeEntry[] | null = null;

    try {
      const probeResp = await requestUrl({ url: rawBase + 'themes.json', method: 'GET' });
      if (probeResp.status === 200) {
        const data = probeResp.json as ThemesIndex;
        if (data.themes?.length) {
          themes = data.themes;
        }
      }
    } catch {
      // themes.json unreachable or not found — will try API listing below
    }

    // ── Step 2: if themes.json didn't work, fall back to directory listing ──
    if (!themes) {
      try {
        themes = await this.listThemesViaApi(apiUrl);
      } catch {
        return 'unreachable';
      }
    }

    if (!themes?.length) {
      return 'unreachable';
    }

    // ── Step 3: ensure target directory exists ──
    if (!(await this.app.vault.adapter.exists(saveDir))) {
      await this.app.vault.createFolder(saveDir);
    }

    // ── Step 4: download each theme file ──
    let downloaded = 0;
    for (const theme of themes) {
      if (!theme.file.endsWith('.md')) continue;

      const vaultPath = `${saveDir}/${theme.file}`;
      if (this.app.vault.getAbstractFileByPath(vaultPath)) continue;

      try {
        const fileResp = await requestUrl({ url: rawBase + theme.file, method: 'GET' });
        if (fileResp.status !== 200) {
          log.warn('failed to download theme file', { file: theme.file, status: fileResp.status });
          continue;
        }
        await this.app.vault.create(vaultPath, fileResp.text);
        downloaded++;
      } catch (err) {
        log.warn('error downloading theme', { file: theme.file, err: String(err) });
      }
    }

    new Notice(t('notice.templates_downloaded', { count: downloaded, dir: saveDir }));
    return 'ok';
  }

  /**
   * List .md files in the themes/ directory via the repo contents API.
   * Used as fallback when themes.json is not present in the repo.
   */
  private async listThemesViaApi(apiUrl: string): Promise<ThemeEntry[]> {
    const resp = await requestUrl({ url: apiUrl, method: 'GET' });
    if (resp.status !== 200) {
      throw new Error(`API directory listing failed: ${resp.status}`);
    }

    const entries = resp.json as ApiDirEntry[];
    if (!Array.isArray(entries)) {
      throw new Error('Unexpected API response format');
    }

    return entries
      .filter((e) => e.name.endsWith('.md'))
      .map((e) => ({
        name: e.name.replace(/\.md$/, ''),
        file: e.name,
      }));
  }

  // ── Fallback: built-in templates when both remotes are unreachable ──

  private async saveFallbackTemplates(saveDir: string): Promise<void> {
    const templates = this.buildFallbackTemplates();

    if (!(await this.app.vault.adapter.exists(saveDir))) {
      await this.app.vault.createFolder(saveDir);
    }

    let downloaded = 0;
    for (const tpl of templates) {
      const vaultPath = `${saveDir}/${tpl.file}`;
      if (this.app.vault.getAbstractFileByPath(vaultPath)) continue;
      await this.app.vault.create(vaultPath, tpl.content);
      downloaded++;
    }

    new Notice(t('notice.templates_downloaded', { count: downloaded, dir: saveDir }));
  }

  private buildFallbackTemplates(): { file: string; content: string }[] {
    const make = (name: string, desc: string, file: string, overrides: Record<string, string | number>) => {
      let fm = `---
wewrite_theme: true
wewrite_theme_name: "${name}"
wewrite_theme_description: "${desc}"
global_margin: 16
global_bg: "#ffffff"
global_font_family: "sans-serif"
global_font_size: 16
global_line_height: 1.8
global_letter_spacing: 0
global_text_color: "#333333"
link_color: "#0366d6"
link_decoration: "underline"
`;
      for (const [k, v] of Object.entries(overrides)) {
        fm += typeof v === 'string' ? `${k}: "${v}"\n` : `${k}: ${v}\n`;
      }
      fm += `---

# ${name}

## Description

${desc}

${t('theme.edit_body')}
`;
      return { file, content: fm };
    };

    return [
      make(t('misc.template_simple_name'), t('misc.template_simple_desc'), 'simple.md', { global_font_size: 15, global_line_height: 1.6 }),
      make(t('misc.template_wechat_name'), t('misc.template_wechat_desc'), 'wechat.md', { global_font_size: 15, link_color: '#576b95' }),
      make(t('misc.template_elegant_name'), t('misc.template_elegant_desc'), 'elegant.md', { global_font_family: 'serif', global_font_size: 17, global_line_height: 1.9, heading_decoration_h1: 'editorial-h1' }),
      make(t('misc.template_dark_name'), t('misc.template_dark_desc'), 'dark.md', { global_bg: '#1a1a2e', global_text_color: '#e0e0e0', link_color: '#64b5f6' }),
      make(t('misc.template_warm_name'), t('misc.template_warm_desc'), 'warm.md', { global_bg: '#fef9ef', global_text_color: '#4a3728', global_font_size: 17, global_line_height: 2.0, link_color: '#c77d20' }),
    ];
  }
}
