// Theme Downloader — fetches pre-built theme templates from GitHub / Gitee
// Mirrors the legacy wewrite theme-manager.ts download pattern.
// GitHub primary, Gitee fallback for users in China.
//
// Index resolution order:
// 1. themes.json (if present in the repo — generated by scanThemes.ts)
// 2. Directory listing via API (GitHub / Gitee contents API)
// 3. Built-in fallback templates (when both remotes are unreachable)

import type { App, RequestUrlResponse } from 'obsidian';
import { Notice, requestUrl, TFile } from 'obsidian';
import { t } from '../i18n';
import { createLogger } from '../utils/logger';
import { parse as parseYaml } from 'yaml';
import { extractFrontmatterBlock } from '../utils/frontmatter';

const log = createLogger('Styles');

// Raw content URLs (for themes.json and raw .md content)
const GITHUB_RAW_BASE = 'https://raw.githubusercontent.com/learnerchen-forever/wewrite/refs/heads/master/themes/';
const GITEE_RAW_BASE = 'https://gitee.com/northern_bank/wewrite/raw/master/themes/';

// API URLs (for directory listing fallback when themes.json is absent)
const GITHUB_API_THEMES = 'https://api.github.com/repos/learnerchen-forever/wewrite/contents/themes/';
const GITEE_API_THEMES = 'https://gitee.com/api/v5/repos/northern_bank/wewrite/contents/themes/';

// Hard per-request timeout — a hung connection must never stall the whole
// download flow (mobile networks often black-hole requests instead of failing).
const REQUEST_TIMEOUT_MS = 15000;
// Extra attempts per theme file — transient mobile network errors are common.
const FILE_RETRY_COUNT = 2;

interface ThemeEntry {
  name: string;
  file: string;
}

interface ThemesIndex {
  themes: ThemeEntry[];
}

interface ApiDirEntry {
  name: string;
  download_url?: string;
  url?: string;
}

interface RemoteResult {
  /** Number of theme files newly created in the vault. */
  downloaded: number;
  /**
   * Number of index files still absent from the vault after the attempt,
   * or -1 when the remote could not be reached at all.
   */
  missing: number;
}

export class ThemeDownloader {
  private app: App;

  constructor(app: App) {
    this.app = app;
  }

  async downloadThemes(saveDir: string): Promise<void> {
    if (!saveDir) {
      new Notice(t('notice.templates_need_styles_dir'));
      return;
    }

    new Notice(t('notice.templates_downloading'));

    // GitHub first; Gitee as backup. A remote only counts as successful when
    // every file of its index is on disk — if it answered but the file
    // downloads failed (rate limit, blocked raw host, encoding, …), the next
    // remote is tried instead of giving up with "0 themes downloaded".
    const remotes: { label: string; rawBase: string; apiUrl: string }[] = [
      { label: 'github', rawBase: GITHUB_RAW_BASE, apiUrl: GITHUB_API_THEMES },
      { label: 'gitee', rawBase: GITEE_RAW_BASE, apiUrl: GITEE_API_THEMES },
    ];

    let totalDownloaded = 0;
    for (const remote of remotes) {
      const result = await this.tryDownload(remote.rawBase, remote.apiUrl, saveDir);
      totalDownloaded += result.downloaded;
      if (result.missing === 0) {
        // Every file of this remote's index is on disk (fresh or pre-existing).
        new Notice(t('notice.templates_downloaded', { count: totalDownloaded, dir: saveDir }));
        return;
      }
      log.warn('theme remote incomplete, trying backup', { label: remote.label, ...result });
    }

    // Both remotes failed — fall back to the built-in templates.
    new Notice(t('notice.templates_offline'));
    await this.saveFallbackTemplates(saveDir);
  }

  /**
   * Attempt to download themes from a single remote.
   * Resolves the index (themes.json, then the contents API), then fetches each
   * missing .md file with per-file retries.
   */
  private async tryDownload(rawBase: string, apiUrl: string, saveDir: string): Promise<RemoteResult> {
    // ── Step 1: resolve the index ──
    let themes: ThemeEntry[] | null = null;

    try {
      const probeResp = await this.getUrl(encodeURI(rawBase + 'themes.json'));
      if (probeResp.status === 200) {
        const data = probeResp.json as ThemesIndex;
        if (data.themes?.length) {
          themes = data.themes;
        }
      }
    } catch (err) {
      // themes.json unreachable or not found — will try API listing below
      log.debug('themes.json probe failed', { err: String(err) });
    }

    if (!themes) {
      try {
        themes = await this.listThemesViaApi(apiUrl);
      } catch (err) {
        log.warn('theme index via API failed', { url: apiUrl, err: String(err) });
        return { downloaded: 0, missing: -1 };
      }
    }

    if (!themes?.length) {
      return { downloaded: 0, missing: -1 };
    }

    // ── Step 2: ensure target directory exists ──
    if (!(await this.app.vault.adapter.exists(saveDir))) {
      await this.app.vault.createFolder(saveDir);
    }

    // ── Step 3: download each theme file ──
    let downloaded = 0;
    let missing = 0;
    for (const theme of themes) {
      if (!theme.file.endsWith('.md')) continue;

      const vaultPath = `${saveDir}/${theme.file}`;
      if (this.app.vault.getAbstractFileByPath(vaultPath)) continue; // already present

      // encodeURI: theme files carry non-ASCII (Chinese) names. iOS's native
      // HTTP layer (NSURLSession) rejects raw non-ASCII URLs, which made the
      // download always fail on iPhone; Android (OkHttp) tolerated them only
      // sometimes. Encode before handing the URL to requestUrl.
      const content = await this.fetchTextWithRetry(encodeURI(rawBase + theme.file));
      if (content === null) {
        missing++;
        log.warn('failed to download theme file', { file: theme.file });
        continue;
      }

      try {
        await this.app.vault.create(vaultPath, content);
        downloaded++;
      } catch (err) {
        missing++;
        log.warn('failed to save theme file', { file: theme.file, err: String(err) });
      }
    }

    return { downloaded, missing };
  }

  /**
   * List .md files in the themes/ directory via the repo contents API.
   * Used as fallback when themes.json is not present in the repo.
   */
  private async listThemesViaApi(apiUrl: string): Promise<ThemeEntry[]> {
    const resp = await this.getUrl(encodeURI(apiUrl));
    if (resp.status !== 200) {
      throw new Error(`API directory listing failed: ${resp.status}`);
    }

    const entries = resp.json as ApiDirEntry[];
    if (!Array.isArray(entries)) {
      throw new Error('Unexpected API response format');
    }

    return entries
      .filter((e) => e.name.endsWith('.md'))
      .map((e) => ({
        name: e.name.replace(/\.md$/, ''),
        file: e.name,
      }));
  }

  /** Fetch a URL's text content with timeout + retries. Returns null on failure. */
  private async fetchTextWithRetry(url: string): Promise<string | null> {
    for (let attempt = 0; attempt <= FILE_RETRY_COUNT; attempt++) {
      try {
        const resp = await this.getUrl(url);
        if (resp.status === 200) {
          return resp.text;
        }
        log.warn('non-200 response', { url, status: resp.status, attempt });
      } catch (err) {
        log.warn('request failed', { url, attempt, err: String(err) });
      }
    }
    return null;
  }

  /**
   * requestUrl with a hard timeout. If the underlying request settles after
   * the timeout, its result is discarded (both handlers are attached, so it
   * can never surface as an unhandled rejection).
   */
  private getUrl(url: string): Promise<RequestUrlResponse> {
    return new Promise((resolve, reject) => {
      let settled = false;
      const timer = window.setTimeout(() => {
        if (settled) return;
        settled = true;
        reject(new Error(`request timed out after ${REQUEST_TIMEOUT_MS}ms`));
      }, REQUEST_TIMEOUT_MS);

      requestUrl({ url, method: 'GET' }).then(
        (resp) => {
          if (settled) return;
          settled = true;
          window.clearTimeout(timer);
          resolve(resp);
        },
        (err) => {
          if (settled) return;
          settled = true;
          window.clearTimeout(timer);
          reject(err instanceof Error ? err : new Error(String(err)));
        },
      );
    });
  }

  // ── Fallback: built-in templates when both remotes are unreachable ──

  private async saveFallbackTemplates(saveDir: string): Promise<void> {
    if (!(await this.app.vault.adapter.exists(saveDir))) {
      await this.app.vault.createFolder(saveDir);
    }
    const { created, repaired } = await this.applyFallbackTemplates(saveDir, { createMissing: true, repairMalformed: true });
    new Notice(t('notice.templates_downloaded', { count: created + repaired, dir: saveDir }));
  }

  /**
   * Public: repair any existing fallback template file whose frontmatter is
   * malformed (e.g. the old builder emitted duplicate YAML keys → "duplicated
   * mapping key"). Never creates new templates — used on plugin load to fix
   * files the previous version already wrote incorrectly. Returns the number
   * of files rewritten.
   */
  async repairFallbackTemplates(saveDir: string): Promise<number> {
    if (!saveDir) return 0;
    const { repaired } = await this.applyFallbackTemplates(saveDir, { createMissing: false, repairMalformed: true });
    return repaired;
  }

  /** Create missing and/or repair malformed fallback templates. */
  private async applyFallbackTemplates(
    saveDir: string,
    opts: { createMissing: boolean; repairMalformed: boolean },
  ): Promise<{ created: number; repaired: number }> {
    if (!opts.createMissing && !opts.repairMalformed) return { created: 0, repaired: 0 };
    const templates = this.buildFallbackTemplates();
    let created = 0;
    let repaired = 0;

    for (const tpl of templates) {
      const vaultPath = `${saveDir}/${tpl.file}`;
      const existing = this.app.vault.getAbstractFileByPath(vaultPath);

      if (!existing) {
        if (opts.createMissing) {
          await this.app.vault.create(vaultPath, tpl.content);
          created++;
        }
        continue;
      }
      if (!opts.repairMalformed) continue;
      if (!(existing instanceof TFile)) continue;

      const current = await this.app.vault.read(existing);
      if (this.isMalformedFrontmatter(current)) {
        await this.app.vault.modify(existing, tpl.content);
        repaired++;
      }
    }

    return { created, repaired };
  }

  /** True when the note's YAML frontmatter cannot be parsed (e.g. duplicate keys). */
  private isMalformedFrontmatter(content: string): boolean {
    const block = extractFrontmatterBlock(content);
    if (block === null) return false;
    try {
      parseYaml(block);
      return false;
    } catch {
      return true;
    }
  }

  private buildFallbackTemplates(): { file: string; content: string }[] {
    const make = (name: string, desc: string, file: string, overrides: Record<string, string | number>) => {
      // Build the frontmatter from a single merged object so no key is emitted
      // twice. Previously the override keys were appended AFTER the base block,
      // which duplicated e.g. global_font_size / global_bg and produced invalid
      // YAML ("duplicated mapping key") that broke theme parsing.
      const data: Record<string, string | number | boolean> = {
        wewrite_theme: true,
        wewrite_theme_name: name,
        wewrite_theme_description: desc,
        global_margin: 16,
        global_bg: '#ffffff',
        global_font_family: 'inherit',
        global_font_size: 16,
        global_line_height: 1.8,
        global_letter_spacing: 0,
        global_text_color: '#333333',
        link_color: '#0366d6',
        link_decoration: 'underline',
        ...overrides,
      };

      let fm = '---\n';
      for (const [k, v] of Object.entries(data)) {
        if (typeof v === 'boolean') {
          fm += `${k}: ${v}\n`;
        } else if (typeof v === 'number') {
          fm += `${k}: ${v}\n`;
        } else {
          const s = String(v).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
          fm += `${k}: "${s}"\n`;
        }
      }
      fm += `---

# ${name}

## Description

${desc}

${t('theme.edit_body')}
`;
      return { file, content: fm };
    };

    return [
      make(t('misc.template_simple_name'), t('misc.template_simple_desc'), 'simple.md', { global_font_size: 15, global_line_height: 1.6 }),
      make(t('misc.template_wechat_name'), t('misc.template_wechat_desc'), 'wechat.md', { global_font_size: 15, link_color: '#576b95' }),
      make(t('misc.template_elegant_name'), t('misc.template_elegant_desc'), 'elegant.md', { global_font_family: 'serif', global_font_size: 17, global_line_height: 1.9, heading_decoration_h1: 'editorial-h1' }),
      make(t('misc.template_dark_name'), t('misc.template_dark_desc'), 'dark.md', { global_bg: '#1a1a2e', global_text_color: '#e0e0e0', link_color: '#64b5f6' }),
      make(t('misc.template_warm_name'), t('misc.template_warm_desc'), 'warm.md', { global_bg: '#fef9ef', global_text_color: '#4a3728', global_font_size: 17, global_line_height: 2.0, link_color: '#c77d20' }),
    ];
  }
}
