// The published theme index (`themes/themes.json`) and the theme notes it
// describes, checked as one artefact.
//
// The index is generated by `tools/scan-themes.mjs`, which cannot import the
// plugin's own hash function (it is a plain Node script; the plugin is
// TypeScript). It therefore reimplements the fingerprint — and that
// duplication is exactly the kind that rots silently: if the two drift, every
// user's themes are reported as "locally modified" and the update dialog
// offers to "restore" notes that were never touched. These assertions make
// that drift fail the suite instead.
//
// The value of a wrong `hash` is not a crash, it is a *plausible* wrong
// answer, which is why it is asserted here rather than trusted.

import * as fs from 'fs';
import * as path from 'path';

import { themeContentHash, normalizeThemeIndex } from '../../../src/styles/theme-index';

const THEMES_DIR = path.join(__dirname, '..', '..', '..', 'themes');
const INDEX_PATH = path.join(THEMES_DIR, 'themes.json');

interface RawEntry {
  name?: unknown;
  file?: unknown;
  description?: unknown;
  descriptionEn?: unknown;
  updated?: unknown;
  hash?: unknown;
}

function readIndexRaw(): { schema?: unknown; generated?: unknown; hashAlgorithm?: unknown; themes: RawEntry[] } {
  return JSON.parse(fs.readFileSync(INDEX_PATH, 'utf8'));
}

describe('themes/themes.json', () => {
  const raw = readIndexRaw();

  it('declares the schema and algorithm the runtime expects', () => {
    expect(raw.schema).toBe(2);
    expect(raw.hashAlgorithm).toBe('fnv1a64');
    expect(typeof raw.generated).toBe('string');
    expect(Number.isNaN(Date.parse(String(raw.generated)))).toBe(false);
  });

  it('parses into an index with usable fingerprints', () => {
    const index = normalizeThemeIndex(raw);
    expect(index).not.toBeNull();
    expect(index!.themes.length).toBeGreaterThan(0);
    for (const entry of index!.themes) {
      expect(entry.hash).toMatch(/^[0-9a-f]{16}$/);
      expect(entry.file).toMatch(/\.md$/);
    }
  });

  it('fingerprints every note the way the plugin does', () => {
    const mismatches: string[] = [];
    for (const entry of raw.themes) {
      const file = String(entry.file);
      const content = fs.readFileSync(path.join(THEMES_DIR, file), 'utf8');
      const expected = themeContentHash(content);
      if (entry.hash !== expected) {
        mismatches.push(`${file}: index ${String(entry.hash)} vs runtime ${expected}`);
      }
    }
    expect(mismatches).toEqual([]);
  });

  it('describes every theme in both languages', () => {
    // The update dialog is the only place a user sees what a theme *is*; an
    // empty string there is a row with no explanation, and it is invisible in
    // review because the JSON is still valid.
    const missing: string[] = [];
    for (const entry of raw.themes) {
      if (typeof entry.description !== 'string' || entry.description.trim() === '') {
        missing.push(`${String(entry.file)} has no description`);
      }
      if (typeof entry.descriptionEn !== 'string' || entry.descriptionEn.trim() === '') {
        missing.push(`${String(entry.file)} has no descriptionEn`);
      }
    }
    expect(missing).toEqual([]);
  });

  it('dates every theme with a plain ISO day', () => {
    const bad: string[] = [];
    for (const entry of raw.themes) {
      const updated = String(entry.updated ?? '');
      if (!/^\d{4}-\d{2}-\d{2}$/.test(updated)) bad.push(`${String(entry.file)}: "${updated}"`);
    }
    expect(bad).toEqual([]);
  });

  it('lists only files that exist, and in the order the shipped set expects', () => {
    const files = raw.themes.map((e) => String(e.file));
    for (const file of files) {
      expect(fs.existsSync(path.join(THEMES_DIR, file))).toBe(true);
    }
    // Guard against a duplicate entry silently shadowing another one: the
    // dialog keys its selection on the file name.
    expect(new Set(files).size).toBe(files.length);
  });

  it('names every theme, so the dialog never shows a bare file name', () => {
    for (const entry of raw.themes) {
      expect(typeof entry.name === 'string' && entry.name.length > 0).toBe(true);
    }
  });
});
