// heading-config.ts — Parse & merge the new heading variable system (§4)
//
// Frontmatter shapes (flat keys, matching the existing theme format):
//   heading.font / .size / .weight / .color / .bgColor / .align
//   heading.marginTop / .marginBottom / .lineHeight / .letterSpacing
//   heading.numbering / .numberingPad / .decoration / .decorationParams
//   heading.scale: { size: { h1Ratio, highRatio, lowRatio, min },
//                    weight: { h1, step, stepEvery, min } }
//   heading.h1…h6.*  — per-level sparse overrides (no scale)
//   custom_values.heading.decoration: [ { id, name, description, template, params } ]
//
// Cascade priority (confirmed in the design, §4.4):
//   default scale → heading (global) → heading.hN (level)
// Size/weight are generated by ratio + floor unless explicitly overridden.

import { getHeadingDecorationMap } from './heading-decoration-library';
import type { DecorationParam, HeadingDecoration } from './heading-decoration-types';

export type HeadingLevel = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
export const HEADING_LEVELS: HeadingLevel[] = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'];

export type HeadingAlign = 'left' | 'center' | 'right';
export type NumberingStyle = 'none' | 'decimal' | 'decimalPad' | 'cjk' | 'roman' | 'circled';
export const NUMBERING_STYLES: NumberingStyle[] = ['none', 'decimal', 'decimalPad', 'cjk', 'roman', 'circled'];

export interface HeadingScaleSizeConfig {
	/** H1 = h1Ratio × body size (default 1.5). */
	h1Ratio?: number;
	/** H1→H2→H3 ratio (default 0.86). */
	highRatio?: number;
	/** H3→H4→H5→H6 ratio (default 0.95). */
	lowRatio?: number;
	/** px floor (default 15). */
	min?: number;
}

export interface HeadingScaleWeightConfig {
	/** Starting weight at H1 (default 700). */
	h1?: number;
	/** Weight delta every stepEvery levels (default -100). */
	step?: number;
	/** Levels between weight steps (default 2 → 700/700/600/600/500/500). */
	stepEvery?: number;
	/** Weight floor (default 500). */
	min?: number;
}

export interface HeadingScaleConfig {
	size?: HeadingScaleSizeConfig;
	weight?: HeadingScaleWeightConfig;
}

export interface HeadingLevelConfig {
	font?: string;
	/** Explicit px or 'auto' (follow the generated scale chain). */
	size?: number | 'auto';
	/** Explicit weight or 'auto' (follow the generated scale chain). */
	weight?: number | 'auto';
	color?: string;
	bgColor?: string;
	align?: HeadingAlign;
	marginTop?: number;
	marginBottom?: number;
	lineHeight?: number;
	letterSpacing?: number;
	numbering?: NumberingStyle;
	numberingPad?: number;
	decoration?: string;
	/** Sparse param overrides merged over the decoration's defaults. */
	decorationParams?: Record<string, string>;
}

export interface HeadingConfig {
	scale?: HeadingScaleConfig;
	/** heading.* values (cascade into every level). */
	global?: HeadingLevelConfig;
	/** heading.h1…h6.* sparse overrides. */
	levels?: Partial<Record<HeadingLevel, HeadingLevelConfig>>;
}

export interface ResolvedHeadingLevel {
	font: string;
	fontSize: number;
	fontWeight: number;
	color: string;
	bgColor: string;
	align: HeadingAlign;
	marginTop: number;
	marginBottom: number;
	lineHeight: number;
	letterSpacing: number;
	numbering: NumberingStyle;
	numberingPad: number;
	decoration: string;
	decorationParams: Record<string, string>;
}

export interface ResolvedHeadingConfig {
	scale: Required<HeadingScaleConfig>;
	levels: Record<HeadingLevel, ResolvedHeadingLevel>;
}

export const DEFAULT_HEADING_SCALE: Required<HeadingScaleConfig> = {
	// Ratios are only used for a custom gradient when a theme explicitly
	// provides scale.size ratios; otherwise the fixed DEFAULT_LEVEL_SIZES apply.
	size: { h1Ratio: 1.5, highRatio: 0.86, lowRatio: 0.95, min: 15 },
	weight: { h1: 700, step: -50, stepEvery: 1, min: 450 },
};

/**
 * Default per-level heading sizes. WeChat is read mostly on small screens, so
 * headings hug the body size and the hierarchy comes from weight + decoration,
 * not size. Shallow near-body gradient with H2==H3 and a fractional H4 (15.5px).
 */
export const DEFAULT_LEVEL_SIZES: Record<HeadingLevel, number> = {
	h1: 17,
	h2: 16,
	h3: 16,
	h4: 15.5,
	h5: 15,
	h6: 14.5,
};

export const DEFAULT_LEVEL_MARGINS: Record<HeadingLevel, { top: number; bottom: number }> = {
	h1: { top: 24, bottom: 16 },
	h2: { top: 20, bottom: 12 },
	h3: { top: 18, bottom: 10 },
	h4: { top: 16, bottom: 8 },
	h5: { top: 14, bottom: 6 },
	h6: { top: 12, bottom: 4 },
};

// ── Parsing ──

const SCALE_SIZE_KEYS = ['h1Ratio', 'highRatio', 'lowRatio', 'min'];
const SCALE_WEIGHT_KEYS = ['h1', 'step', 'stepEvery', 'min'];
const HEADING_SCALAR_KEYS = new Set([
	'font', 'size', 'weight', 'color', 'bgColor', 'align',
	'marginTop', 'marginBottom', 'lineHeight', 'letterSpacing',
	'numbering', 'numberingPad', 'decoration',
]);

function isObj(v: unknown): v is Record<string, unknown> {
	return typeof v === 'object' && v !== null && !Array.isArray(v);
}

function toNumber(v: unknown): number | undefined {
	if (typeof v === 'number') return Number.isFinite(v) ? v : undefined;
	if (typeof v === 'string' && v.trim() !== '') {
		const n = Number(v);
		return Number.isFinite(n) ? n : undefined;
	}
	return undefined;
}

function asStringMap(v: unknown): Record<string, string> {
	const out: Record<string, string> = {};
	if (isObj(v)) {
		for (const [k, val] of Object.entries(v)) {
			if (typeof val === 'string') out[k] = val;
		}
	}
	return out;
}

function setScalar(target: HeadingLevelConfig, key: string, value: unknown): void {
	switch (key) {
		case 'size': {
			const n = toNumber(value);
			if (n !== undefined) target.size = n;
			else if (value === 'auto') target.size = 'auto';
			break;
		}
		case 'weight': {
			const n = toNumber(value);
			if (n !== undefined) target.weight = n;
			else if (value === 'auto') target.weight = 'auto';
			break;
		}
		case 'marginTop':
		case 'marginBottom':
		case 'lineHeight':
		case 'letterSpacing':
		case 'numberingPad': {
			const n = toNumber(value);
			if (n !== undefined) (target as Record<string, unknown>)[key] = n;
			break;
		}
		case 'align': {
			if (value === 'left' || value === 'center' || value === 'right') target.align = value;
			break;
		}
		case 'numbering': {
			if (typeof value === 'string' && (NUMBERING_STYLES as string[]).includes(value)) {
				target.numbering = value as NumberingStyle;
			}
			break;
		}
		case 'font':
		case 'color':
		case 'bgColor':
		case 'decoration': {
			if (typeof value === 'string' && value) (target as Record<string, unknown>)[key] = value;
			break;
		}
	}
}

function parseScaleObject(raw: unknown): HeadingScaleConfig {
	const scale: HeadingScaleConfig = {};
	if (!isObj(raw)) return scale;

	if (isObj(raw.size)) {
		scale.size = {};
		for (const key of SCALE_SIZE_KEYS) {
			const n = toNumber(raw.size[key]);
			if (n !== undefined) scale.size[key as keyof HeadingScaleSizeConfig] = n;
		}
	}
	if (isObj(raw.weight)) {
		scale.weight = {};
		for (const key of SCALE_WEIGHT_KEYS) {
			const n = toNumber(raw.weight[key]);
			if (n !== undefined) scale.weight[key as keyof HeadingScaleWeightConfig] = n;
		}
	}
	return scale;
}

function setScalePath(config: HeadingConfig, rest: string, value: unknown): void {
	const [group, key] = rest.split('.');
	const n = toNumber(value);
	if (n === undefined) return;

	if (group === 'size' && key && SCALE_SIZE_KEYS.includes(key)) {
		config.scale = config.scale || {};
		config.scale.size = config.scale.size || {};
		config.scale.size[key as keyof HeadingScaleSizeConfig] = n;
	} else if (group === 'weight' && key && SCALE_WEIGHT_KEYS.includes(key)) {
		config.scale = config.scale || {};
		config.scale.weight = config.scale.weight || {};
		config.scale.weight[key as keyof HeadingScaleWeightConfig] = n;
	}
}

/**
 * Apply one heading frontmatter entry. `path` is the key without the
 * 'heading' prefix, e.g. 'font', 'h2.size', 'scale.size.h1Ratio'.
 */
function applyHeadingKey(config: HeadingConfig, path: string, value: unknown): void {
	// scale
	if (path === 'scale') {
		if (isObj(value)) {
			config.scale = { ...config.scale, ...parseScaleObject(value) };
		}
		return;
	}
	if (path.startsWith('scale.')) {
		setScalePath(config, path.slice('scale.'.length), value);
		return;
	}

	// global decorationParams (object + flat forms)
	if (path === 'decorationParams') {
		config.global = config.global || {};
		config.global.decorationParams = { ...(config.global.decorationParams || {}), ...asStringMap(value) };
		return;
	}
	if (path.startsWith('decorationParams.')) {
		if (typeof value === 'string') {
			config.global = config.global || {};
			config.global.decorationParams = config.global.decorationParams || {};
			config.global.decorationParams[path.slice('decorationParams.'.length)] = value;
		}
		return;
	}

	// per-level
	const levelMatch = /^(h[1-6])(?:\.(.*))?$/.exec(path);
	if (levelMatch) {
		const level = levelMatch[1] as HeadingLevel;
		const rest = levelMatch[2];

		if (rest === undefined) {
			// nested object form: heading.h1: { color: accent }
			if (isObj(value)) {
				for (const [k, v] of Object.entries(value)) applyHeadingKey(config, `${level}.${k}`, v);
			}
			return;
		}

		if (rest === 'decorationParams') {
			const target = (config.levels = config.levels || {});
			const lvl = (target[level] = target[level] || {});
			lvl.decorationParams = { ...(lvl.decorationParams || {}), ...asStringMap(value) };
			return;
		}
		if (rest.startsWith('decorationParams.')) {
			if (typeof value === 'string') {
				const target = (config.levels = config.levels || {});
				const lvl = (target[level] = target[level] || {});
				lvl.decorationParams = lvl.decorationParams || {};
				lvl.decorationParams[rest.slice('decorationParams.'.length)] = value;
			}
			return;
		}
		if (!HEADING_SCALAR_KEYS.has(rest)) return;
		const target = (config.levels = config.levels || {});
		const lvl = (target[level] = target[level] || {});
		setScalar(lvl, rest, value);
		return;
	}

	// global scalar (unknown keys are ignored — v3 slots like border stay untouched)
	if (!HEADING_SCALAR_KEYS.has(path)) return;
	setScalar(config.global = config.global || {}, path, value);
}

function parseCustomDecorations(customValues: unknown): HeadingDecoration[] {
	if (!isObj(customValues)) return [];
	const list = customValues['heading.decoration'];
	if (!Array.isArray(list)) return [];

	const out: HeadingDecoration[] = [];
	for (const item of list) {
		const d = item as Record<string, unknown> | null;
		if (!d || typeof d.id !== 'string' || !d.id) continue;
		if (typeof d.name !== 'string' || !d.name) continue;
		if (typeof d.template !== 'string' || !d.template) continue;

		const params: Record<string, DecorationParam> = {};
		if (isObj(d.params)) {
			for (const [pk, pv] of Object.entries(d.params)) {
				const def = pv as Record<string, unknown> | null;
				if (!def || typeof def.type !== 'string' || typeof def.default !== 'string') continue;
				params[pk] = {
					type: def.type as DecorationParam['type'],
					label: typeof def.label === 'string' ? def.label : pk,
					default: def.default,
				};
			}
		}

		out.push({
			id: d.id,
			name: d.name,
			description: typeof d.description === 'string' ? d.description : '',
			builtin: false,
			template: d.template,
			params,
			family: 'composite',
			suggestedLevels: 'all',
		});
	}
	return out;
}

/** Parse the new heading config (and custom decorations) from theme frontmatter. */
export function parseHeadingFrontmatter(
	frontmatter: Record<string, unknown>,
): { config: HeadingConfig; customDecorations: HeadingDecoration[] } {
	const config: HeadingConfig = {};
	const customDecorations = parseCustomDecorations(frontmatter['custom_values']);

	for (const [key, value] of Object.entries(frontmatter)) {
		if (key === 'heading' && isObj(value)) {
			for (const [k, v] of Object.entries(value)) applyHeadingKey(config, k, v);
			continue;
		}
		if (key.startsWith('heading.')) {
			applyHeadingKey(config, key.slice('heading.'.length), value);
		}
	}

	return { config, customDecorations };
}

// ── Merging / resolution ──

export function computeHeadingScale(
	scale: HeadingScaleConfig | undefined,
	bodySize: number,
): Record<HeadingLevel, { fontSize: number; fontWeight: number }> {
	const w = { ...DEFAULT_HEADING_SCALE.weight, ...(scale?.weight || {}) } as Required<HeadingScaleWeightConfig>;

	// Custom gradient only when the theme explicitly provides size ratios; the
	// default is the fixed small-screen DEFAULT_LEVEL_SIZES (so H2==H3 and the
	// fractional H4 hold even though a pure ratio chain can't).
	const explicitSize = scale?.size || {};
	const hasRatio = explicitSize.h1Ratio !== undefined
		|| explicitSize.highRatio !== undefined
		|| explicitSize.lowRatio !== undefined;

	let sizes: Record<HeadingLevel, number>;
	if (hasRatio) {
		const s = { ...DEFAULT_HEADING_SCALE.size, ...explicitSize } as Required<HeadingScaleSizeConfig>;
		let cur = s.h1Ratio * bodySize;
		const raw = [cur];
		cur *= s.highRatio;
		raw.push(cur);
		cur *= s.highRatio;
		raw.push(cur);
		for (let i = 0; i < 3; i++) {
			cur *= s.lowRatio;
			raw.push(cur);
		}
		const min = s.min;
		const sizeArr = raw.map(v => Math.max(Math.round(v), min));
		sizes = Object.fromEntries(HEADING_LEVELS.map((level, i) => [level, sizeArr[i]])) as Record<HeadingLevel, number>;
	} else {
		sizes = { ...DEFAULT_LEVEL_SIZES };
	}

	const weights = HEADING_LEVELS.map((_, i) => Math.max(w.h1 + w.step * Math.floor(i / w.stepEvery), w.min));

	return Object.fromEntries(HEADING_LEVELS.map((level, i) => [level, { fontSize: sizes[level], fontWeight: weights[i] }])) as Record<HeadingLevel, { fontSize: number; fontWeight: number }>;
}

/** Merge scale → global → level and fill every field with its final value. */
export function resolveHeadingConfig(config: HeadingConfig | undefined, bodySize: number): ResolvedHeadingConfig {
	const cfg = config || {};
	const global = cfg.global || {};
	const generated = computeHeadingScale(cfg.scale, bodySize);
	const levels = {} as Record<HeadingLevel, ResolvedHeadingLevel>;

	for (const level of HEADING_LEVELS) {
		const lvl = cfg.levels?.[level] || {};
		const base = generated[level];

		levels[level] = {
			font: lvl.font ?? global.font ?? 'inherit',
			fontSize: lvl.size !== undefined
				? (lvl.size === 'auto' ? base.fontSize : lvl.size)
				: (global.size !== undefined
					? (global.size === 'auto' ? base.fontSize : global.size)
					: base.fontSize),
			fontWeight: lvl.weight !== undefined
				? (lvl.weight === 'auto' ? base.fontWeight : lvl.weight)
				: (global.weight !== undefined
					? (global.weight === 'auto' ? base.fontWeight : global.weight)
					: base.fontWeight),
			color: lvl.color ?? global.color ?? 'text',
			bgColor: lvl.bgColor ?? global.bgColor ?? 'transparent',
			align: lvl.align ?? global.align ?? 'left',
			marginTop: lvl.marginTop ?? global.marginTop ?? DEFAULT_LEVEL_MARGINS[level].top,
			marginBottom: lvl.marginBottom ?? global.marginBottom ?? DEFAULT_LEVEL_MARGINS[level].bottom,
			lineHeight: lvl.lineHeight ?? global.lineHeight ?? 1.3,
			letterSpacing: lvl.letterSpacing ?? global.letterSpacing ?? 0,
			numbering: lvl.numbering ?? global.numbering ?? 'none',
			numberingPad: lvl.numberingPad ?? global.numberingPad ?? 2,
			decoration: lvl.decoration ?? global.decoration ?? 'none',
			decorationParams: { ...(global.decorationParams || {}), ...(lvl.decorationParams || {}) },
		};
	}

	const mergedScale: Required<HeadingScaleConfig> = {
		size: { ...DEFAULT_HEADING_SCALE.size, ...(cfg.scale?.size || {}) } as Required<HeadingScaleSizeConfig>,
		weight: { ...DEFAULT_HEADING_SCALE.weight, ...(cfg.scale?.weight || {}) } as Required<HeadingScaleWeightConfig>,
	};

	return { scale: mergedScale, levels };
}

/** Resolve a decoration id (builtin or custom) with sparse param overrides. */
export function resolveHeadingDecoration(
	decorationId: string,
	paramsOverride: Record<string, string> | undefined,
	customDecorations: HeadingDecoration[] = [],
): { decoration: HeadingDecoration; params: Record<string, string> } {
	const map = { ...getHeadingDecorationMap() };
	for (const c of customDecorations) {
		if (!map[c.id]) map[c.id] = c;
	}

	const decoration = map[decorationId] || map['none'];
	const params: Record<string, string> = {};
	for (const [k, v] of Object.entries(decoration.params)) {
		params[k] = v.default;
	}
	if (paramsOverride) {
		for (const [k, v] of Object.entries(paramsOverride)) {
			params[k] = v;
		}
	}
	return { decoration, params };
}

// ── Serialization (theme editor save) ──

/** True when a flat frontmatter key belongs to the new heading variable system. */
export function isHeadingVarKey(key: string): boolean {
	if (!key.startsWith('heading.')) return false;
	const rest = key.slice('heading.'.length);
	if (rest === 'scale') return true;
	if (rest.startsWith('scale.')) {
		const [group, sub] = rest.slice('scale.'.length).split('.');
		return (group === 'size' && SCALE_SIZE_KEYS.includes(sub))
			|| (group === 'weight' && SCALE_WEIGHT_KEYS.includes(sub));
	}
	if (rest === 'decorationParams' || rest.startsWith('decorationParams.')) return true;

	const levelMatch = /^(h[1-6])(?:\.(.+))?$/.exec(rest);
	if (levelMatch) {
		const suffix = levelMatch[2];
		if (!suffix) return false; // nested object form is not written as a flat key
		if (suffix === 'decorationParams' || suffix.startsWith('decorationParams.')) return true;
		return HEADING_SCALAR_KEYS.has(suffix);
	}
	return HEADING_SCALAR_KEYS.has(rest);
}

/** Default-valued fields are omitted from the saved frontmatter for clean output. */
function isDefaultHeadingValue(key: string, v: unknown): boolean {
	switch (key) {
		case 'font': return v === 'inherit';
		case 'color': return v === 'text';
		case 'bgColor': return v === 'transparent';
		case 'align': return v === 'left';
		case 'numbering': return v === 'none';
		case 'decoration': return v === 'none';
		case 'numberingPad': return v === 2;
		default: return false;
	}
}

/** Serialize a heading config back to flat frontmatter keys (heading.* / heading.hN.*). */
export function headingConfigToFrontmatter(config: HeadingConfig | undefined): Record<string, unknown> {
	const out: Record<string, unknown> = {};
	if (!config) return out;

	const global = config.global;
	if (global) {
		for (const [k, v] of Object.entries(global)) {
			if (k === 'decorationParams') {
				if (v && Object.keys(v).length > 0) out['heading.decorationParams'] = { ...v };
			} else if (v !== undefined && !isDefaultHeadingValue(k, v)) {
				out[`heading.${k}`] = v;
			}
		}
	}

	if (config.scale) {
		const scale: Record<string, unknown> = {};
		if (config.scale.size && Object.keys(config.scale.size).length > 0) {
			scale.size = { ...config.scale.size };
		}
		if (config.scale.weight && Object.keys(config.scale.weight).length > 0) {
			scale.weight = { ...config.scale.weight };
		}
		if (Object.keys(scale).length > 0) out['heading.scale'] = scale;
	}

	if (config.levels) {
		for (const [level, lvl] of Object.entries(config.levels)) {
			if (!lvl) continue;
			for (const [k, v] of Object.entries(lvl)) {
				if (k === 'decorationParams') {
					if (v && Object.keys(v).length > 0) {
						out[`heading.${level}.decorationParams`] = { ...v };
					}
				} else if (v !== undefined && !isDefaultHeadingValue(k, v)) {
					out[`heading.${level}.${k}`] = v;
				}
			}
		}
	}

	return out;
}

/** Serialize user-defined heading decorations for custom_values.heading.decoration. */
export function customDecorationsToFrontmatter(decorations: HeadingDecoration[] | undefined): Record<string, unknown> | null {
	if (!decorations || decorations.length === 0) return null;
	return {
		'heading.decoration': decorations.map(d => {
			const params: Record<string, unknown> = {};
			for (const [k, v] of Object.entries(d.params)) {
				params[k] = { type: v.type, label: v.label, default: v.default };
			}
			return {
				id: d.id,
				name: d.name,
				...(d.description ? { description: d.description } : {}),
				template: d.template,
				...(Object.keys(params).length > 0 ? { params } : {}),
			};
		}),
	};
}
